# fly.toml app configuration file generated for articlear on 2023-06-07T01:08:06+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "articlear"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3300
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
